export const set = [
    {
        id: 1,
        label: "Fullname:",
        inputname: "fullname",
        type: "fullname",
        placeholder: "Enter Your fullname",
    },
    {
      id: 2,
      label: "Username:",
      inputname: "username",
      type: "username",
      placeholder: "Enter Your Username",
    },
    {
        id: 3,
        label: "email:",
        inputname: "email",
        type: "email",
        placeholder: "Enter Your email",
    },
    {
        id: 4,
        label: "Phone No.:",
        inputname: "phone_number",
        type: "phone_number",
        placeholder: "Enter Your Phone No.",
    },
    {
      id: 5,
      label: "Password:",
      inputname: "password",
      type: "password",
      placeholder: "Enter Your Password",
    },
    {
        id: 6,
        label: "Street_name:",
        inputname: "street_name",
        type: "street_name",
        placeholder: "Enter Your Street_name",
    },
    {
        id: 7,
        label: "Street No.:",
        inputname: "street_number",
        type: "street_number",
        placeholder: "Enter Your Street No.",
    },
    {
        id: 8,
        label: "Location:",
        inputname: "location",
        type: "location",
        placeholder: "Enter Your Location",
    },
    {
        id: 9,
        label: "LGA:",
        inputname: "lga",
        type: "lga",
        placeholder: "Enter Your LGA",
    },
    {
        id: 10,
        label: "State:",
        inputname: "state",
        type: "state",
        placeholder: "Enter Your State",
    },
]